### ISSUE TITLE
 Module build failed: Error:        Something wrong with provided resources.       Make sure 'options.resources' is String or Array of Strings.

### ISSUE THREAD

**Issue by IAMtheIAM** [shakacode/sass-resources-loader#38]
The plugin throws error with webpack 3.1.0
```
                  {
                     loader: 'sass-resources-loader',
                     options: {
                        resources: ['./src/assets/styles/variables.scss', './src/assets/styles/mixins.scss'],
                     }
                  },
```
```

Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
```

Upon debugging webpack, it appears  `sass-resources-loader\lib\utils\parseResources.js` line 34 is returning blank. Glob.sync is not returning the absolute path. So in `sass-resources-loader\lib\loader.js` line 54, `var resourcesLocations ` is set to empty

**Comment by Maushundb** [comment]
Getting the same with Webpack 2.6

**Comment by IAMtheIAM** [comment]
More at this [issue 40](https://github.com/shakacode/sass-resources-loader/issues/40)

**Comment by alexfedoseev** [comment]
I believe this can be closed. `1.3.1` and few notes added in https://github.com/shakacode/sass-resources-loader/commit/f3d2cf6245abac5cc7e03799ab2a810d84a61b91 should resolve these issues.

**Comment by aFcFzF** [comment]
>  resources: ['./src/assets/styles/variables.scss', './src/assets/styles/mixins.scss'],

the path in options.resources must be a absolute path, eg: 
`resources: [path.resolve(__dirname,  './src/assets/styles/variables.scss')]`

**Comment by pangz1** [comment]
> > resources: ['./src/assets/styles/variables.scss', './src/assets/styles/mixins.scss'],
> 
> the path in options.resources must be a absolute path, eg:
> `resources: [path.resolve(__dirname, './src/assets/styles/variables.scss')]`
> 
> path.resolve is needed,good lucky!

using absolute path still get the error

**Comment by justin808** [comment]
@pangz1 any chance that you can dig into this. If a PR is needed, I'll review.

**Comment by dkaraush** [comment]
This error can be misleading. It says that the resources array is empty in config, but really there can be just zero files resolved by `glob`.
I spent half an hour, added logs into `parseResources.js` and only after I realized that I used wrong config with wrong pathes. 🤦‍♂️

**Comment by justin808** [comment]
@dkaraush @Tomburgs any thoughts if we could have a PR that could give a better error message?

**Comment by dkaraush** [comment]
Ok, I think this error should be turned into warning, and before it should be another check.
The thing is, if there are no resource files found by `glob` (for example, I setup as `globalStyles/*.scss`, but haven't put any files there yet), then the webpack will just fail to build. In my opinion this can be a little warning, that there is just extra rule in webpack config. (`!resourcesLocations.length` returns `true` if it is an empty array)
I'm not very familiar with webpack philosophy, maybe that's ok, actually.
And another check can be extended even before putting those resources into `glob`.

I made a PR of my thoughts, feel free to add any comments and change it.

**Comment by Tomburgs** [comment]
@dkaraush I think your solution might bring more confusion, although I do agree that this should be a non-fatal error.
I was thinking perhaps in `utils/parseResources` under the `isArrayOfStrings` statement we could check if any of the paths didn't resolve any files and, if so, display a warning message?

Something like so:
```javascript
if (isArrayOfStrings(locations)) {
    logger.debug('options.resources is Array of Strings:', true);

    return locations.reduce((resolvedFiles, directory) => {
        const files = glob.sync(directory);

        if (files.length === 0) {
            logger.warn(`
                Couldn't find any files under the ${directory} directory.
                Did you forget to resolve this to an absolute path with path.resolve?
            `);
        }

        return [...resolvedFiles, ...files];
    }, []);
}
```

Let me know what you think @justin808 & @dkaraush.

**Comment by dkaraush** [comment]
Yes, I agree with you, that would be much more clear. But keep in mind that single string can also bring an empty array of files.
You can make those changes in my PR or make your own and abandon mine. I don't like how testing of console.log works there, but didn't find any better solution.

**Comment by justin808** [comment]
I like what @Tomburgs said, but I think the error should be fatal, as warnings might be ignored.

**Comment by Tomburgs** [comment]
Done. Have a look at #134 @justin808 & @dkaraush!
